apiVersion: apps/v1
kind: Deployment
metadata:
  name: sagar-deployment
  labels:
    app: sagar-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: sagar-app
  template:
    metadata:
      labels:
        app: sagar-app
    spec:
      containers:
      - name: sagar-container
        image: kicbase/echo-server:latest
        ports:
        - containerPort: 8080