apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      volumeMounts:
        - mountPath: "/data"
          name: mypdvolume
  volumes:
    - name: mypdvolume
      persistentVolumeClaim:
        claimName: pvc0001